#!/usr/bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6
bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config normal_border_color "#4f110f"
bspc config focused_border_color "#ff4b38"
bspc config presel_feedback_color "#ff4b38"

bspc rule -a Wrapper-2.0 state=floating border=off
bspc rule -a Xfce4-appfinder state=floating border=off
bspc rule -a org.gnome.FileRoller state=floating
