# $HOME/.config/alacritty/alacritty.toml
# by Rito Ghosh 2023-10-06

# Alacritty now uses TOML formatting for its config files.
# This is a simple example.

# There are the specification here: https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd
# It is not obvious how it translates to TOML. But it is extremely straightforward.

# example: WINDOW, COLORS, etc. are tables, and should be represented as [window], [colors], respectively.
# specifics of variables go under them. e.g.- look under "dynamic_padding" under-
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#window
# write `dynamic_padding = true` (without backticks -`) under the table [window]
# for variables with multiple values, use "dotted keys". Like setting `padding.x = 5` under [window].
# This is simple. If not clear, do several trials and errors.

[window]

opacity = 0.7

padding = { x = 10, y = 10 }
dynamic_padding = true

[font]
size = 8

#normal.family = "Maple Mono NF"
#bold.family = "Maple Mono NF"
#italic.family = "Maple Mono NF"
#bold_italic.family = "Maple Mono NF"
normal.family = "Jetbrains Mono Nerd Font"
bold.family = "Jetbrains Mono Nerd Font"
italic.family = "Jetbrains Mono Nerd Font"
bold_italic.family = "Jetbrains Mono Nerd Font"

[colors.primary]

# background color
background = "#252525"
# foreground (text) color
foreground = "#edddbd"

[terminal.shell]

# run tmux as shell (interactive shell is set to fish in tmux configuration ~/.config/tmux/tmux.conf)
program = "/usr/bin/tmux"
args = ["attach"]

# Tip: for inspiration, look for values in the source code files of your favorite VS Code themes, and use the color picker in
# Google to test colors before setting a value, or simply using an editor such as VS Code where colors are displayed in a 
# small box when a HEX is detected by the editor.
